### ISSUE TITLE
Нет обработки ошибочного ответа юзера

### ISSUE THREAD

**Issue by victorbaldin56** [Barkir/Tree#4]
https://github.com/Barkir/Tree/blob/73496a1fe6f0b97afa170f4c79a2895a10490485/tree.cpp#L133C1-L146C2

Здесь буквально UB если юзер ответил не yes или no

**Comment by victorbaldin56** [comment]
<details>
<summary>Вывод, если нажать ctrl+D</summary>

```
./a.out
sh: line 1: dot: command not found
NBA CHAMP?
tree.cpp:133:8: runtime error: execution reached the end of a value-returning function without returning a value
```

</details>

**Comment by Barkir** [comment]
пофиксил
